[package]
name = "cli-client"
version = "0.1.0"
edition = "2021"

[dependencies]
speech-center-client = { path = "../speech-center-client" }

bytes = "1.1.0"
hound = "3.4"
structopt = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["full"] }